export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const TWEETS_LOADED_REQUEST = "TWEETS_LOADED_REQUEST";
export const TWEETS_LOADED_SUCCESS = "TWEETS_LOADED_SUCCESS";
export const TWEETS_LOADED_FAILURE = "TWEETS_LOADED_FAILURE";

export const TWEET_LOADED_REQUEST = "TWEET_LOADED_REQUEST";
export const TWEET_LOADED_SUCCESS = "TWEET_LOADED_SUCCESS";
export const TWEET_LOADED_FAILURE = "TWEET_LOADED_FAILURE";

export const TWEET_CREATED_REQUEST = "TWEET_CREATED_REQUEST";
export const TWEET_CREATED_SUCCESS = "TWEET_CREATED_SUCCESS";
export const TWEET_CREATED_FAILURE = "TWEET_CREATED_FAILURE";

export const UI_RESET_ERROR = "UI_RESET_ERROR";
