export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const TWEETS_LOADED = "TWEETS_LOADED";
export const TWEETS_CREATED = "TWEETS_CREATED";
export const UI_RESET_ERROR = "UI_RESET_ERROR";
